tap "homebrew/services"

# Git
brew "git"
brew "git-lfs"

# Local development
brew "php"
brew "composer"
brew "mariadb", restart_service: true
brew "phpmyadmin"
brew "node"
brew "python"

# Command line configuration
brew "starship"
brew "zsh-syntax-highlighting"

# Misc.
brew "youtube-dl"
